/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BLL.BLL_PhatSinh;
import DAL.DAL_PhatSinh;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author dthan
 */
public class frmMain extends javax.swing.JFrame {

    private frmDichVu1 frmDichVu = null;
    private frmKhachHang1 frmKhachHang = null;
    private frmPhatSinh1 frmPhatSinh = null;
    private frmPhatSinhChiTiet1 frmPhatSinhChiTiet = null;
    private frmPhieuThu1 frmPhieuThu = null;
    private frmThongKe frmThongKe1 = null;
    private frmSuaMayTinh frmSuaMayTinh1 = null;

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setTitle("Trang chủ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jdesktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        menuDangXuat = new javax.swing.JMenuItem();
        menuThoat = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuKhachHang = new javax.swing.JMenuItem();
        menuPhieuThu = new javax.swing.JMenuItem();
        menuPhatSinh = new javax.swing.JMenuItem();
        menuPhatSinhChiTiet = new javax.swing.JMenuItem();
        menuDichVu = new javax.swing.JMenuItem();
        menuChiTiet = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        jMenu6.setText("jMenu6");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jdesktopLayout = new javax.swing.GroupLayout(jdesktop);
        jdesktop.setLayout(jdesktopLayout);
        jdesktopLayout.setHorizontalGroup(
            jdesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );
        jdesktopLayout.setVerticalGroup(
            jdesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 485, Short.MAX_VALUE)
        );

        jMenu4.setText("Trang chủ");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        menuDangXuat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuDangXuat.setText("Đăng xuất");
        menuDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDangXuatActionPerformed(evt);
            }
        });
        jMenu4.add(menuDangXuat);

        menuThoat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuThoat.setText("Thoát");
        menuThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuThoatActionPerformed(evt);
            }
        });
        jMenu4.add(menuThoat);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Hệ thống");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        menuKhachHang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuKhachHang.setText("Khách hàng");
        menuKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKhachHangActionPerformed(evt);
            }
        });
        jMenu5.add(menuKhachHang);

        menuPhieuThu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuPhieuThu.setText("Phiếu thu");
        menuPhieuThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPhieuThuActionPerformed(evt);
            }
        });
        jMenu5.add(menuPhieuThu);

        menuPhatSinh.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuPhatSinh.setText("Phát sinh");
        menuPhatSinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPhatSinhActionPerformed(evt);
            }
        });
        jMenu5.add(menuPhatSinh);

        menuPhatSinhChiTiet.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuPhatSinhChiTiet.setText("Phát sinh chi tiết");
        menuPhatSinhChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPhatSinhChiTietActionPerformed(evt);
            }
        });
        jMenu5.add(menuPhatSinhChiTiet);

        menuDichVu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuDichVu.setText("Dịch vụ");
        menuDichVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDichVuActionPerformed(evt);
            }
        });
        jMenu5.add(menuDichVu);

        menuChiTiet.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuChiTiet.setText("Chi Tiết");
        menuChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuChiTietActionPerformed(evt);
            }
        });
        jMenu5.add(menuChiTiet);

        jMenuBar1.add(jMenu5);

        jMenu7.setText("Thống kê");
        jMenu7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jCheckBoxMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Thống kê chi tiết");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        jMenu7.add(jCheckBoxMenuItem1);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdesktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdesktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuThoatActionPerformed
        int a = JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát không?", "Thống báo", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            System.exit(0);
        } else {
        }
    }//GEN-LAST:event_menuThoatActionPerformed

    private void menuPhatSinhChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPhatSinhChiTietActionPerformed
        if (frmPhatSinhChiTiet == null) {
            try {
                frmPhatSinhChiTiet = new frmPhatSinhChiTiet1();
                jdesktop.add(frmPhatSinhChiTiet);
                frmPhatSinhChiTiet.setLocation(this.getWidth() / 2 - frmPhatSinhChiTiet.getWidth() / 2, (this.getHeight() - 20) / 2 - frmPhatSinhChiTiet.getHeight() / 2 - 20);
                frmPhatSinhChiTiet.setVisible(true);
            } catch (Exception ex) {
                Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            frmPhatSinhChiTiet.setLocation(this.getWidth() / 2 - frmPhatSinhChiTiet.getWidth() / 2, (this.getHeight() - 20) / 2 - frmPhatSinhChiTiet.getHeight() / 2 - 20);
            frmPhatSinhChiTiet.setVisible(true);
            frmPhatSinhChiTiet.toFront();
        }
    }//GEN-LAST:event_menuPhatSinhChiTietActionPerformed

    private void menuPhieuThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPhieuThuActionPerformed
        if (frmPhieuThu == null) {
            try {
                frmPhieuThu = new frmPhieuThu1();
                jdesktop.add(frmPhieuThu);
                frmPhieuThu.setLocation(this.getWidth() / 2 - frmPhieuThu.getWidth() / 2, (this.getHeight() - 20) / 2 - frmPhieuThu.getHeight() / 2 - 20);
                frmPhieuThu.setVisible(true);
            } catch (Exception ex) {
                Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            frmPhieuThu.setLocation(this.getWidth() / 2 - frmPhieuThu.getWidth() / 2, (this.getHeight() - 20) / 2 - frmPhieuThu.getHeight() / 2 - 20);
            frmPhieuThu.setVisible(true);
            frmPhieuThu.toFront();
        }
    }//GEN-LAST:event_menuPhieuThuActionPerformed

    private void menuKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKhachHangActionPerformed

        if (frmKhachHang == null) {
            try {
                frmKhachHang = new frmKhachHang1();
                jdesktop.add(frmKhachHang);
                frmKhachHang.setLocation(this.getWidth() / 2 - frmKhachHang.getWidth() / 2, (this.getHeight() - 20) / 2 - frmKhachHang.getHeight() / 2 - 20);
                frmKhachHang.setVisible(true);
            } catch (Exception ex) {
                Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            frmKhachHang.setLocation(this.getWidth() / 2 - frmKhachHang.getWidth() / 2, (this.getHeight() - 20) / 2 - frmKhachHang.getHeight() / 2 - 20);
            frmKhachHang.setVisible(true);
            frmKhachHang.toFront();
        }
    }//GEN-LAST:event_menuKhachHangActionPerformed

    private void menuPhatSinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPhatSinhActionPerformed
        if (frmPhatSinh == null) {
            try {
                frmPhatSinh = new frmPhatSinh1();
                jdesktop.add(frmPhatSinh);
                frmPhatSinh.setLocation(this.getWidth() / 2 - frmPhatSinh.getWidth() / 2, (this.getHeight() - 20) / 2 - frmPhatSinh.getHeight() / 2 - 20);
                frmPhatSinh.setVisible(true);
            } catch (Exception ex) {
                Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            frmPhatSinh.setLocation(this.getWidth() / 2 - frmPhatSinh.getWidth() / 2, (this.getHeight() - 20) / 2 - frmPhatSinh.getHeight() / 2 - 20);
            frmPhatSinh.setVisible(true);
            frmPhatSinh.toFront();
        }
    }//GEN-LAST:event_menuPhatSinhActionPerformed

    private void menuDichVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDichVuActionPerformed
        if (frmDichVu == null) {
            try {
                frmDichVu = new frmDichVu1();
                jdesktop.add(frmDichVu);
                frmDichVu.setLocation(this.getWidth() / 2 - frmDichVu.getWidth() / 2, (this.getHeight() - 20) / 2 - frmDichVu.getHeight() / 2 - 20);
                frmDichVu.setVisible(true);
            } catch (Exception ex) {
                Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            frmDichVu.setLocation(this.getWidth() / 2 - frmDichVu.getWidth() / 2, (this.getHeight() - 20) / 2 - frmDichVu.getHeight() / 2 - 20);
            frmDichVu.setVisible(true);
            frmDichVu.toFront();
        }
    }//GEN-LAST:event_menuDichVuActionPerformed

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
        if (frmThongKe1 == null) {
            try {
                frmThongKe1 = new frmThongKe();
                jdesktop.add(frmThongKe1);
                frmThongKe1.setLocation(this.getWidth() / 2 - frmThongKe1.getWidth() / 2, (this.getHeight() - 20) / 2 - frmThongKe1.getHeight() / 2 - 20);
                frmThongKe1.setVisible(true);
            } catch (Exception ex) {
                Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            frmThongKe1.setLocation(this.getWidth() / 2 - frmThongKe1.getWidth() / 2, (this.getHeight() - 20) / 2 - frmThongKe1.getHeight() / 2 - 20);
            frmThongKe1.setVisible(true);
            frmThongKe1.toFront();
        }
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    private void menuChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuChiTietActionPerformed
        if (frmSuaMayTinh1 == null) {
            try {
                frmSuaMayTinh1 = new frmSuaMayTinh();
                jdesktop.add(frmSuaMayTinh1);
                frmSuaMayTinh1.setLocation(this.getWidth() / 2 - frmSuaMayTinh1.getWidth() / 2, (this.getHeight() - 20) / 2 - frmSuaMayTinh1.getHeight() / 2 - 20);
                frmSuaMayTinh1.setVisible(true);
            } catch (Exception ex) {
                Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            frmSuaMayTinh1.setLocation(this.getWidth() / 2 - frmSuaMayTinh1.getWidth() / 2, (this.getHeight() - 20) / 2 - frmSuaMayTinh1.getHeight() / 2 - 20);
            frmSuaMayTinh1.setVisible(true);
            frmSuaMayTinh1.toFront();
        }
    }//GEN-LAST:event_menuChiTietActionPerformed

    private void menuDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDangXuatActionPerformed
        this.dispose();
        frmDangNhap frmDN = new frmDangNhap();
        frmDN.setVisible(true);
    }//GEN-LAST:event_menuDangXuatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JDesktopPane jdesktop;
    private javax.swing.JMenuItem menuChiTiet;
    private javax.swing.JMenuItem menuDangXuat;
    private javax.swing.JMenuItem menuDichVu;
    private javax.swing.JMenuItem menuKhachHang;
    private javax.swing.JMenuItem menuPhatSinh;
    private javax.swing.JMenuItem menuPhatSinhChiTiet;
    private javax.swing.JMenuItem menuPhieuThu;
    private javax.swing.JMenuItem menuThoat;
    // End of variables declaration//GEN-END:variables
}
