/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import BLL.BLL_PhieuThu;
import DAL.DAL_PhieuThu;
import BLL.BLL_KhacHang;
import ET.ET_PhieuThu;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author dthan
 */
public class frmPhieuThu1 extends javax.swing.JInternalFrame {

    private BLL_PhieuThu bll_phieuThu = new BLL_PhieuThu();
    private BLL_KhacHang bll_khachHang = new BLL_KhacHang();

    /**
     * Creates new form frmPhieuThu1
     */
    public frmPhieuThu1() throws Exception {
        initComponents();
        initComponents();
        hienThi();
        hienThiPhieuThu();
        comboboxMaKhachHang();
        java.util.Date date = new java.util.Date();
        dtpNgayThu.setDate(date);
        AutoCompleteDecorator.decorate(cbbMaKhachHang);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSoPhieuThu = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnXoa = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnSua = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnThoat = new javax.swing.JButton();
        txtSoTien = new javax.swing.JTextField();
        cbbMaKhachHang = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dtpNgayThu = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPhieuThu = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        btnMoi = new javax.swing.JButton();
        btnsapXep = new javax.swing.JButton();
        btnsapXep1 = new javax.swing.JButton();

        txtSoPhieuThu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnThem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add_24px.png"))); // NOI18N
        btnThem.setText("THÊM");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Mã khách hàng");

        btnXoa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete_24px.png"))); // NOI18N
        btnXoa.setText("XOÁ");
        btnXoa.setToolTipText("");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Số phiếu thu");

        btnSua.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/edit_24px.png"))); // NOI18N
        btnSua.setText("SỬA");
        btnSua.setToolTipText("");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Số tiền");

        btnThoat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/shutdown_24px.png"))); // NOI18N
        btnThoat.setText("THOÁT");
        btnThoat.setToolTipText("");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        txtSoTien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtSoTien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSoTienKeyPressed(evt);
            }
        });

        cbbMaKhachHang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PHIẾU THU");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        dtpNgayThu.setDateFormatString("dd/MM/yyyy");
        dtpNgayThu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        tblPhieuThu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblPhieuThu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Số phiếu thu", "Mã khách hàng", "Ngày thu", "Số tiền"
            }
        ));
        tblPhieuThu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPhieuThuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPhieuThu);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Ngày thu");

        btnMoi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/refresh_24px.png"))); // NOI18N
        btnMoi.setText("MỚI");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        btnsapXep.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnsapXep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/enter_24px.png"))); // NOI18N
        btnsapXep.setText("SẮP XẾP GIẢM");
        btnsapXep.setToolTipText("");
        btnsapXep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsapXepActionPerformed(evt);
            }
        });

        btnsapXep1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnsapXep1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/enter_24px.png"))); // NOI18N
        btnsapXep1.setText("SẮP XẾP TĂNG");
        btnsapXep1.setToolTipText("");
        btnsapXep1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsapXep1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel7)
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnMoi)
                                .addGap(36, 36, 36))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSoPhieuThu, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(cbbMaKhachHang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtSoTien)
                            .addComponent(dtpNgayThu, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnThem)
                        .addGap(48, 48, 48)
                        .addComponent(btnXoa)
                        .addGap(45, 45, 45)
                        .addComponent(btnSua)
                        .addGap(39, 39, 39)
                        .addComponent(btnThoat)
                        .addGap(0, 67, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnsapXep)
                        .addGap(18, 18, 18)
                        .addComponent(btnsapXep1)
                        .addGap(37, 37, 37)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSoPhieuThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(dtpNgayThu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSoTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(cbbMaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsapXep)
                    .addComponent(btnsapXep1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMoi)
                    .addComponent(btnThem)
                    .addComponent(btnXoa)
                    .addComponent(btnSua)
                    .addComponent(btnThoat))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        java.sql.Date sqlDate = new java.sql.Date(dtpNgayThu.getDate().getTime());

        ET_PhieuThu et_PhieuThu = new ET_PhieuThu(txtSoPhieuThu.getText(), cbbMaKhachHang.getSelectedItem().toString(), sqlDate, Integer.parseInt(txtSoTien.getText()));
        if (txtSoPhieuThu.getText().compareTo("") == 0 || Integer.parseInt(txtSoTien.getText()) <= 0) {
            JOptionPane.showMessageDialog(null, "Vui lòng điền đầy đủ thông tin");
        } else {
            try {
                if (bll_phieuThu.checkTonTaiPhieuThu(txtSoPhieuThu.getText())) {
                    JOptionPane.showMessageDialog(null, "Đã tồn tại số phiếu thu này");
                } else {
                    et_PhieuThu = new ET_PhieuThu(txtSoPhieuThu.getText(), cbbMaKhachHang.getSelectedItem().toString(), sqlDate, Integer.parseInt(txtSoTien.getText()));
                    if (bll_phieuThu.themPhieuThu(et_PhieuThu)) {
                        JOptionPane.showMessageDialog(rootPane, "Thêm không thành công");
                        reset();
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Thêm thành công");
                        reset();
                        hienThi();
                        hienThiPhieuThu();
                    }
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        java.sql.Date sqlDate = new java.sql.Date(dtpNgayThu.getDate().getTime());
        ET_PhieuThu et_PhieuThu = new ET_PhieuThu(txtSoPhieuThu.getText(), cbbMaKhachHang.getSelectedItem().toString(), sqlDate, Integer.parseInt(txtSoTien.getText()));

        int row = tblPhieuThu.getSelectedRow();
        if (row >= 0) {
            et_PhieuThu = new ET_PhieuThu(txtSoPhieuThu.getText(), cbbMaKhachHang.getSelectedItem().toString(), sqlDate, Integer.parseInt(txtSoTien.getText()));
            try {
                if (bll_phieuThu.xoaPhieuThu(et_PhieuThu)) {
                    JOptionPane.showMessageDialog(rootPane, "Xoá không thành công");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Xóa thành công");
                    try {
                        hienThiPhieuThu();
                        reset();
                    } catch (Exception ex) {
                        Logger.getLogger(frmDichVu1.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn phiếu thu");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        java.sql.Date sqlDate = new java.sql.Date(dtpNgayThu.getDate().getTime());
        ET_PhieuThu et_PhieuThu = new ET_PhieuThu(txtSoPhieuThu.getText(), cbbMaKhachHang.getSelectedItem().toString(), sqlDate, Integer.parseInt(txtSoTien.getText()));

        if (txtSoPhieuThu.getText().compareTo("") == 0 || Integer.parseInt(txtSoTien.getText()) <= 0) {
            JOptionPane.showMessageDialog(null, "Vui lòng điền đầy đủ thông tin");
        } else {
            try {
                bll_phieuThu.suaPhieuThu(et_PhieuThu);
                JOptionPane.showMessageDialog(rootPane, "Sửa thành công");
                try {
                    hienThiPhieuThu();
                    reset();
                } catch (Exception ex) {
                    Logger.getLogger(frmDichVu1.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(rootPane, "Sửa không thành công");
            }
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        int kq = JOptionPane.showConfirmDialog(null, "Bạn có muốn thoát không", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (kq == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_btnThoatActionPerformed

    private void tblPhieuThuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPhieuThuMouseClicked
        int row = tblPhieuThu.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tblPhieuThu.getModel();
        txtSoPhieuThu.setText(model.getValueAt(row, 0).toString());
        cbbMaKhachHang.setSelectedItem(model.getValueAt(row, 1).toString());
        String date = model.getValueAt(row, 2).toString();
        try {
            dtpNgayThu.setDate(new SimpleDateFormat("yyyy-MM-dd").parse(date));
        } catch (ParseException ex) {
            Logger.getLogger(frmKhachHang1.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtSoTien.setText(model.getValueAt(row, 3).toString());

    }//GEN-LAST:event_tblPhieuThuMouseClicked

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        try {
            reset();

        } catch (Exception ex) {
            Logger.getLogger(frmPhieuThu1.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnMoiActionPerformed

    private void txtSoTienKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoTienKeyPressed
                char gia = evt.getKeyChar();
        if (Character.isLetter(gia)) {
            txtSoTien.setEditable(false);
            JOptionPane.showMessageDialog(null, "Vui lòng nhập số");
        } else {
        txtSoTien.setEditable(true);
        }
    }//GEN-LAST:event_txtSoTienKeyPressed

    private void btnsapXepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsapXepActionPerformed
        DefaultTableModel model = (DefaultTableModel) tblPhieuThu.getModel();
        model.setRowCount(0);
        ResultSet rs = null;
        try {
            rs = bll_phieuThu.sapXepPhieuThu();
        } catch (Exception ex) {
            Logger.getLogger(frmDichVu1.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            while (rs.next()) {
                Object[] col = new Object[4];
                for (int i = 1; i <= 4; i++) {
                    try {
                        col[i - 1] = rs.getObject(i);
                    } catch (SQLException ex) {
                        Logger.getLogger(frmDichVu1.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                model.addRow(col);
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmDichVu1.class.getName()).log(Level.SEVERE, null, ex);
        }
        tblPhieuThu.setModel(model);
        txtSoTien.setText("0");
    }//GEN-LAST:event_btnsapXepActionPerformed

    private void btnsapXep1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsapXep1ActionPerformed
        try {
            hienThiPhieuThu();
        } catch (Exception ex) {
            Logger.getLogger(frmPhieuThu1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnsapXep1ActionPerformed
    private void hienThi() {
        DefaultTableModel model = (DefaultTableModel) tblPhieuThu.getModel();
        model.setRowCount(0);
        model.setColumnCount(0);
        model.addColumn("Số phiếu thu");
        model.addColumn("Mã khách hàng");
        model.addColumn("Ngày lập phiếu");
        model.addColumn("Số tiền");
        tblPhieuThu.setModel(model);
    }

    // hiển thị danh mục lên table
    private void hienThiPhieuThu() throws Exception {
        DefaultTableModel model = (DefaultTableModel) tblPhieuThu.getModel();
        model.setRowCount(0);
        ResultSet rs = bll_phieuThu.hienThiPhieuThu();
        while (rs.next()) {
            Object[] col = new Object[4];
            for (int i = 1; i <= 4; i++) {
                col[i - 1] = rs.getObject(i);
            }
            model.addRow(col);
        }
        tblPhieuThu.setModel(model);
        txtSoTien.setText("0");
    }

    public void comboboxMaKhachHang() throws Exception {
        cbbMaKhachHang.removeAllItems();
        ResultSet rs = bll_khachHang.hienThiKhachHang();
        while (rs.next()) {
            cbbMaKhachHang.addItem(rs.getString("MaKH"));
        }
    }

    public void reset() throws Exception {
        txtSoPhieuThu.setText("");
        txtSoTien.setText("0");
        cbbMaKhachHang.setSelectedIndex(0);
        dtpNgayThu.setDate(new Date());
        hienThiPhieuThu();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnsapXep;
    private javax.swing.JButton btnsapXep1;
    private javax.swing.JComboBox<String> cbbMaKhachHang;
    private com.toedter.calendar.JDateChooser dtpNgayThu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPhieuThu;
    private javax.swing.JTextField txtSoPhieuThu;
    private javax.swing.JTextField txtSoTien;
    // End of variables declaration//GEN-END:variables
}
