/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import BLL.BLL_PhatSinhChiTiet;
import DAL.DAL_PhatSinhChiTiet;
import BLL.BLL_PhatSinh;
import BLL.BLL_DichVu;
import ET.ET_PhatSinhChiTiet;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author dthan
 */
public class frmPhatSinhChiTiet1 extends javax.swing.JInternalFrame {

    private BLL_PhatSinhChiTiet bll_phatSinhChiTiet = new BLL_PhatSinhChiTiet();
    private BLL_PhatSinh bll_phatSinh = new BLL_PhatSinh();
    private BLL_DichVu bll_dichVu = new BLL_DichVu();

    /**
     * Creates new form frmPhatSinhChiTiet1
     */
    public frmPhatSinhChiTiet1() throws Exception {
        initComponents();
        initComponents();
        hienThi();
        hienThiPhatSinhChiTiet();

        comboboxSoPhieu();
        comboboxMaDichVu();
        AutoCompleteDecorator.decorate(cbbMaDichVu);
        AutoCompleteDecorator.decorate(cbbSoPhieu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbbSoPhieu = new javax.swing.JComboBox<>();
        txtSoLuongSuDung = new javax.swing.JTextField();
        cbbMaDichVu = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPhatSinhChiTiet = new javax.swing.JTable();
        btnMoi = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnSua = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnThoat = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        cbbSoPhieu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtSoLuongSuDung.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtSoLuongSuDung.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSoLuongSuDungKeyPressed(evt);
            }
        });

        cbbMaDichVu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PHÁT SINH CHI TIẾT");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        tblPhatSinhChiTiet.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblPhatSinhChiTiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Số phiếu", "Mã dịch vụ", "Số lượng sử dụng"
            }
        ));
        tblPhatSinhChiTiet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPhatSinhChiTietMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPhatSinhChiTiet);

        btnMoi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/refresh_24px.png"))); // NOI18N
        btnMoi.setText("MỚI");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        btnThem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add_24px.png"))); // NOI18N
        btnThem.setText("THÊM");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Delete_24px.png"))); // NOI18N
        btnXoa.setText("XOÁ");
        btnXoa.setToolTipText("");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Mã dịch vụ");

        btnSua.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/edit_24px.png"))); // NOI18N
        btnSua.setText("SỬA");
        btnSua.setToolTipText("");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Số phiếu");

        btnThoat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/shutdown_24px.png"))); // NOI18N
        btnThoat.setText("THOÁT");
        btnThoat.setToolTipText("");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Số lượng sử dụng");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnMoi)
                        .addGap(36, 36, 36)
                        .addComponent(btnThem)
                        .addGap(48, 48, 48)
                        .addComponent(btnXoa)
                        .addGap(45, 45, 45)
                        .addComponent(btnSua)
                        .addGap(39, 39, 39)
                        .addComponent(btnThoat))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbbSoPhieu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbbMaDichVu, 0, 159, Short.MAX_VALUE))
                        .addGap(66, 66, 66)
                        .addComponent(jLabel8)
                        .addGap(34, 34, 34)
                        .addComponent(txtSoLuongSuDung, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(txtSoLuongSuDung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbSoPhieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbbMaDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMoi)
                    .addComponent(btnThem)
                    .addComponent(btnXoa)
                    .addComponent(btnSua)
                    .addComponent(btnThoat))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblPhatSinhChiTietMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPhatSinhChiTietMouseClicked
        int row = tblPhatSinhChiTiet.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tblPhatSinhChiTiet.getModel();
        cbbSoPhieu.setSelectedItem(model.getValueAt(row, 0).toString());
        cbbMaDichVu.setSelectedItem(model.getValueAt(row, 1).toString());
        txtSoLuongSuDung.setText(model.getValueAt(row, 2).toString());
    }//GEN-LAST:event_tblPhatSinhChiTietMouseClicked

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        try {
            reset();
        } catch (Exception ex) {
            Logger.getLogger(frmPhatSinhChiTiet1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnMoiActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        ET_PhatSinhChiTiet et_phatSinhChiTiet = new ET_PhatSinhChiTiet(cbbSoPhieu.getSelectedItem().toString(), cbbMaDichVu.getSelectedItem().toString(), Integer.parseInt(txtSoLuongSuDung.getText()));

        if (Integer.parseInt(txtSoLuongSuDung.getText()) <= 0) {
            JOptionPane.showMessageDialog(null, "Vui lòng điền đầy đủ thông tin");
        } else {
            try {
                if (bll_phatSinhChiTiet.themPhatSinhChiTiet(et_phatSinhChiTiet)) {
                    JOptionPane.showMessageDialog(rootPane, "Thêm không thành công");
                    try {
                        reset();
                        hienThiPhatSinhChiTiet();
                    } catch (Exception ex) {
                        Logger.getLogger(frmPhatSinhChiTiet1.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Thêm thành công");
                    try {
                        hienThiPhatSinhChiTiet();
                        reset();
                    } catch (Exception ex) {
                        Logger.getLogger(frmPhatSinhChiTiet1.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed

        ET_PhatSinhChiTiet et_phatSinhChiTiet = new ET_PhatSinhChiTiet(cbbSoPhieu.getSelectedItem().toString(), cbbMaDichVu.getSelectedItem().toString(), Integer.parseInt(txtSoLuongSuDung.getText()));

        int row = tblPhatSinhChiTiet.getSelectedRow();
        if (row >= 0) {
            try {
                if (bll_phatSinhChiTiet.xoaPhatSinhChiTiet(et_phatSinhChiTiet)) {
                    JOptionPane.showMessageDialog(rootPane, "Xoá không thành công");
                    try {
                        reset();
                    } catch (Exception ex) {
                        Logger.getLogger(frmPhatSinhChiTiet1.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    try {
                        hienThiPhatSinhChiTiet();
                    } catch (Exception ex) {
                        Logger.getLogger(frmPhatSinhChiTiet1.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Xóa thành công");
                    try {
                        hienThiPhatSinhChiTiet();
                        reset();
                        hienThiPhatSinhChiTiet();
                    } catch (Exception ex) {
                        Logger.getLogger(frmDichVu1.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }

            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn khách hàng");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        int kq = JOptionPane.showConfirmDialog(null, "Bạn có muốn thoát không", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (kq == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        ET_PhatSinhChiTiet et_phatSinhChiTiet = new ET_PhatSinhChiTiet(cbbSoPhieu.getSelectedItem().toString(), cbbMaDichVu.getSelectedItem().toString(), Integer.parseInt(txtSoLuongSuDung.getText()));

        if (Integer.parseInt(txtSoLuongSuDung.getText()) <= 0) {
            JOptionPane.showMessageDialog(null, "Vui lòng điền đầy đủ thông tin");
        } else {
            try {
                bll_phatSinhChiTiet.suaPhatSinhChiTiet(et_phatSinhChiTiet);
                JOptionPane.showMessageDialog(rootPane, "Sửa thành công");
                try {
                    hienThiPhatSinhChiTiet();
                    reset();
                } catch (Exception ex) {
                    Logger.getLogger(frmDichVu1.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(rootPane, "Sửa không thành công");
            }
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void txtSoLuongSuDungKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoLuongSuDungKeyPressed
        char gia = evt.getKeyChar();
        if (Character.isLetter(gia)) {
            txtSoLuongSuDung.setEditable(false);
            JOptionPane.showMessageDialog(null, "Vui lòng nhập số");
        } else {
            txtSoLuongSuDung.setEditable(true);
        }
    }//GEN-LAST:event_txtSoLuongSuDungKeyPressed
    private void hienThi() {
        DefaultTableModel model = (DefaultTableModel) tblPhatSinhChiTiet.getModel();
        model.setRowCount(0);
        model.setColumnCount(0);
        model.addColumn("Số phiếu");
        model.addColumn("Mã dịch vụ");
        model.addColumn("Số lượng sử dụng");
        tblPhatSinhChiTiet.setModel(model);
    }

    private void hienThiPhatSinhChiTiet() throws Exception {
        DefaultTableModel model = (DefaultTableModel) tblPhatSinhChiTiet.getModel();
        model.setRowCount(0);
        ResultSet rs = bll_phatSinhChiTiet.hienThiPhatSinhChiTiet();
        while (rs.next()) {
            Object[] col = new Object[3];
            for (int i = 1; i <= 3; i++) {
                col[i - 1] = rs.getObject(i);
            }
            model.addRow(col);
        }
        tblPhatSinhChiTiet.setModel(model);
        txtSoLuongSuDung.setText("0");
    }

    public void comboboxSoPhieu() throws Exception {
        cbbSoPhieu.removeAllItems();
        ResultSet rs = bll_phatSinh.hienThiPhatSinh();
        while (rs.next()) {
            cbbSoPhieu.addItem(rs.getString("SoPhieu"));
        }
    }

    public void comboboxMaDichVu() throws Exception {
        cbbMaDichVu.removeAllItems();
        ResultSet rs = bll_dichVu.hienThiDichVu();
        while (rs.next()) {
            cbbMaDichVu.addItem(rs.getString("MaDV"));
        }
    }

    public void reset() throws Exception {
        cbbMaDichVu.setSelectedIndex(0);
        cbbSoPhieu.setSelectedIndex(0);
        txtSoLuongSuDung.setText("0");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbbMaDichVu;
    private javax.swing.JComboBox<String> cbbSoPhieu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPhatSinhChiTiet;
    private javax.swing.JTextField txtSoLuongSuDung;
    // End of variables declaration//GEN-END:variables
}
