/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import javax.swing.JOptionPane;
import BLL.BLL_PhatSinhChiTiet;
import DAL.DAL_PhatSinhChiTiet;
import BLL.BLL_PhatSinh;
import DAL.DAL_PhatSinh;
import BLL.BLL_KhacHang;
import DAL.DAL_KhachHang;
import BLL.BLL_DichVu;
import BLL.BLL_DichVu;
import DAL.DAL_DichVu;
import ET.ET_PhatSinhChiTiet;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author dthan
 */
public class frmSuaMayTinh extends javax.swing.JInternalFrame {

    private BLL_KhacHang bll_KhachHang = new BLL_KhacHang();
    private BLL_PhatSinh bll_PhatSinh = new BLL_PhatSinh();
    private BLL_PhatSinhChiTiet bll_PhatSinhChiTiet = new BLL_PhatSinhChiTiet();
    private BLL_DichVu bll_DichVu = new BLL_DichVu();

    /**
     * Creates new form frmSuaMayTinh
     */
    public frmSuaMayTinh() {
        initComponents();
        hienThi();
        txtTongSoPhieu.setEditable(false);
        txtTenKhach.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMaKhach = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTenKhach = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        dtpNgaySinh = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblChiTietPhieu = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPhieu = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        btnThoat = new javax.swing.JButton();
        txtTongSoPhieu = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtTongSoMuc = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtTongPhiDichVu = new javax.swing.JTextField();

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SỬA CHỮA MÁY TÍNH");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        txtMaKhach.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtMaKhach.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMaKhachFocusLost(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Các phiếu sửa chữa");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Tên khách thuê");

        txtTenKhach.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Ngày sinh");

        dtpNgaySinh.setDateFormatString("dd/MM/yyyy");
        dtpNgaySinh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Mã khách");

        tblChiTietPhieu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã dịch vụ", "Tên dịch vụ", "Số tiền"
            }
        ));
        tblChiTietPhieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblChiTietPhieuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblChiTietPhieu);

        tblPhieu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Số phiếuu", "Ngày lậpp"
            }
        ));
        tblPhieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPhieuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPhieu);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Chi tiết các dịch vụ của phiếu");

        btnThoat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/shutdown_24px.png"))); // NOI18N
        btnThoat.setText("THOÁT");
        btnThoat.setToolTipText("");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        txtTongSoPhieu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Tổng số phiếu");

        txtTongSoMuc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Tổng số mục");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Tổng phí dịch vụ");

        txtTongPhiDichVu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(txtMaKhach, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(txtTenKhach, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(dtpNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(txtTongSoPhieu, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(53, 53, 53))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTongSoMuc, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTongPhiDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(147, 147, 147))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThoat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dtpNgaySinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMaKhach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTenKhach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10)))
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTongSoPhieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtTongSoMuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTongPhiDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnThoat)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        int kq = JOptionPane.showConfirmDialog(null, "Bạn có muốn thoát không", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (kq == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_btnThoatActionPerformed
    private void hienThiKhachHang(String soPhieu) throws Exception {
        ResultSet rs = bll_KhachHang.layKhachHang(soPhieu);
        DefaultTableModel model = (DefaultTableModel) tblPhieu.getModel();
        model.setNumRows(0);
        while (rs.next()) {
            ResultSet rss = bll_PhatSinh.laySoPhieu_KhachHang(rs.getObject(1).toString());
            while (rss.next()) {
                Object[] col = new Object[2];
                for (int i = 1; i <= 2; i++) {
                    col[i - 1] = rss.getObject(i);
                }
                model.addRow(col);
            }
            txtTenKhach.setText(rs.getObject(2).toString());
            dtpNgaySinh.setDate(rs.getDate(3));
            txtTongSoPhieu.setText(bll_PhatSinh.tongSoPhieu(rs.getObject(1).toString()));
        }
    }

    private void hienThiDichVu(String soPhieu) throws Exception {
        ResultSet rs = bll_PhatSinhChiTiet.timPhatSinh(soPhieu);
        DefaultTableModel model = (DefaultTableModel) tblChiTietPhieu.getModel();
        int tinhTien = 0;
        int tong=0;
        model.setNumRows(0);
        while (rs.next()) {
            Object[] col = new Object[3];
            tinhTien = (Integer.parseInt(rs.getObject(3).toString())) * (Integer.parseInt(bll_DichVu.layGiaDichVu(rs.getObject(2).toString())));
            for (int i = 1; i <= 3; i++) {
                if (i == 1) {
                    col[i - 1] = rs.getObject(2);
                } else if (i == 2) {
                    col[i - 1] = bll_DichVu.layTenDichVu(rs.getObject(2).toString());
                } else {
                    col[i - 1] = tinhTien;
                }
            }
            model.addRow(col);
            tong=tong+tinhTien;
            txtTongSoMuc.setText(bll_PhatSinhChiTiet.tongSoMuc(rs.getObject(1).toString()));
        }
        txtTongPhiDichVu.setText(String.valueOf(tong));
    }
    private void txtMaKhachFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMaKhachFocusLost

        try {
            if (txtMaKhach.getText().compareTo("") == 0) {
                JOptionPane.showMessageDialog(null, "Vui lòng nhập mã khách hàng");
            } else if (bll_KhachHang.checkTonTaiKhachHang(txtMaKhach.getText())) {
                hienThiKhachHang(txtMaKhach.getText());
            } else {
                JOptionPane.showMessageDialog(null, "Không có mã khách hàng này");
            }
        } catch (Exception ex) {
            Logger.getLogger(frmSuaMayTinh.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtMaKhachFocusLost

    private void tblChiTietPhieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChiTietPhieuMouseClicked


    }//GEN-LAST:event_tblChiTietPhieuMouseClicked

    private void tblPhieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPhieuMouseClicked
        int row = tblPhieu.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tblPhieu.getModel();
        String madichVu = model.getValueAt(row, 0).toString();
        try {
            hienThiDichVu(madichVu); // TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(frmSuaMayTinh.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblPhieuMouseClicked

    public void hienThi() {
        DefaultTableModel model = (DefaultTableModel) tblPhieu.getModel();
        model.setColumnCount(0);
        model.setRowCount(0);
        model.addColumn("Số phiếu");
        model.addColumn("Ngày lập");
        tblPhieu.setModel(model);
        DefaultTableModel modell = (DefaultTableModel) tblChiTietPhieu.getModel();
        modell.setColumnCount(0);
        modell.setRowCount(0);
        modell.addColumn("Mã dịch vụ");
        modell.addColumn("Tên dịch vụ");
        modell.addColumn("Số tiền");
        tblChiTietPhieu.setModel(modell);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThoat;
    private com.toedter.calendar.JDateChooser dtpNgaySinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblChiTietPhieu;
    private javax.swing.JTable tblPhieu;
    private javax.swing.JTextField txtMaKhach;
    private javax.swing.JTextField txtTenKhach;
    private javax.swing.JTextField txtTongPhiDichVu;
    private javax.swing.JTextField txtTongSoMuc;
    private javax.swing.JTextField txtTongSoPhieu;
    // End of variables declaration//GEN-END:variables
}
